<div class="siqrp_form_row siqrp_form_select">
	<div class="siqrp_form_label">
		<?php
			echo $taxonomy->labels->name;
		?>:
		<?php
		if ( $taxonomy->_builtin == false ) {
			echo " <span class='siqrp_help dashicons dashicons-info' data-help='" . esc_attr( __( 'This belongs to a custom taxonomy', 'related-posts-by-searchiq' ) ) . "'></span>";
		}
		?>
	</div>
	<div>
		<select name=weight[tax][<?php echo $taxonomy->name; ?>]">
			<option value="no" <?php echo ( ( ! $weight && ! $require ) ? 'selected' : null ); ?> > 
				<?php _e( 'do not consider', 'related-posts-by-searchiq' ); ?>
			</option>
			<option value="consider" <?php echo ( ( $weight == 1 && ! $require ) ? 'selected' : null ); ?> >
				<?php _e( 'consider', 'related-posts-by-searchiq' ); ?>
			</option>
			<option value="consider_extra" <?php echo ( ( $weight > 1 && ! $require ) ? 'selected' : null ); ?> >
				<?php _e( 'consider with extra weight', 'related-posts-by-searchiq' ); ?>
			</option>
			<option value="require_one" <?php echo ( ( $require == 1 ) ? 'selected' : null ); ?>>
				<?php printf( __( 'require at least one %s in common', 'related-posts-by-searchiq' ), strtolower( $taxonomy->labels->singular_name ) ); ?>
			</option>
			<option value="require_more" <?php echo ( ( $require == 2 ) ? 'selected' : null ); ?>>
				<?php printf( __( 'require more than one %s in common', 'related-posts-by-searchiq' ), strtolower( $taxonomy->labels->singular_name ) ); ?>
			</option>
		</select>
	</div>
</div>
