<div class="siqrp_form_row siqrp_form_radio <?php esc_attr_e( $class ); ?>">
	<div>
		<input
			type="radio" 
			name="<?php esc_attr_e( $option ); ?>" 
			id="siqrp-<?php esc_attr_e( $option . '_' . $value ); ?>" 
			value="<?php esc_attr_e( $value ); ?>" 
			<?php checked( $value === siqrp_get_option_thumbnail( $option, 'grid' ) ); ?>
		/>
		<label for="siqrp-<?php echo $option . '_' . $value; ?>"><?php echo $desc; ?></label>
	</div>
</div>
