<div class="siqrp_form_row siqrp_form_select_label">
	<div class="siqrp_form_label"><?php esc_html_e( $desc, 'related-posts-by-searchiq' ); ?></div>
	<div>
		<select name="<?php echo esc_attr( $name ); ?>" id="<?php echo esc_attr( $name ); ?>">
			<?php foreach ( $options as $key => $val ) { ?>
			<?php
				/* translators: 1: thumbnail size name, 2: width (in pixels), 3: height (in pixels) */
				$option_name = sprintf( __( '%1$s (%2$sx%3$s)', 'related-posts-by-searchiq' ), $key, $val['width'], $val['height'] );
				?>
				<option
					value="<?php echo esc_attr( $key ); ?>"
					<?php selected( siqrp_get_option_thumbnail( $name, 'grid' ), $key ); ?>>
					<?php echo esc_html( $option_name ); ?>
				</option>
			<?php } ?>
		</select>
	</div>
</div>
